<?php

namespace ContainerKocdCxf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChannelSpecificMessageFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Factory\ChannelSpecificMessageFactory' shared autowired service.
     *
     * @return \App\Factory\ChannelSpecificMessageFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Factory/ChannelSpecificMessageFactory.php';

        return $container->privates['App\\Factory\\ChannelSpecificMessageFactory'] = new \App\Factory\ChannelSpecificMessageFactory();
    }
}
