<?php

namespace ContainerKocdCxf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMessageHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\CQ\CommandHandler\SendMessageHandler' shared autowired service.
     *
     * @return \App\CQ\CommandHandler\SendMessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CQ/CommandHandler/SendMessageHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/MessageFactory.php';

        return $container->privates['App\\CQ\\CommandHandler\\SendMessageHandler'] = new \App\CQ\CommandHandler\SendMessageHandler(($container->privates['App\\Factory\\MessageFactory'] ??= new \App\Factory\MessageFactory()), ($container->services['messenger.bus.default.test-bus'] ?? $container->load('getMessenger_Bus_Default_TestbusService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
