<?php

namespace ContainerKocdCxf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZenstruckMessengerTest_TransportRegistryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'zenstruck_messenger_test.transport_registry' shared service.
     *
     * @return \Zenstruck\Messenger\Test\Transport\TestTransportRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/messenger-test/src/Transport/TestTransportRegistry.php';

        $container->services['zenstruck_messenger_test.transport_registry'] = $instance = new \Zenstruck\Messenger\Test\Transport\TestTransportRegistry();

        $instance->register('async', ($container->privates['messenger.transport.async'] ?? $container->load('getMessenger_Transport_AsyncService')));
        $instance->register('failed', ($container->privates['messenger.transport.failed'] ?? $container->load('getMessenger_Transport_FailedService')));
        $instance->register('sync', ($container->privates['messenger.transport.sync'] ?? $container->load('getMessenger_Transport_SyncService')));

        return $instance;
    }
}
