<?php

namespace ContainerKocdCxf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZenstruckMessengerTest_BusRegistryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'zenstruck_messenger_test.bus_registry' shared service.
     *
     * @return \Zenstruck\Messenger\Test\Bus\TestBusRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/messenger-test/src/Bus/TestBusRegistry.php';

        $container->services['zenstruck_messenger_test.bus_registry'] = $instance = new \Zenstruck\Messenger\Test\Bus\TestBusRegistry();

        $instance->register('messenger.bus.default', ($container->services['messenger.bus.default.test-bus'] ?? $container->load('getMessenger_Bus_Default_TestbusService')));

        return $instance;
    }
}
