<?php

namespace ContainerIxKRv3f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_TestbusService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'messenger.bus.default.test-bus' shared autowired service.
     *
     * @return \Zenstruck\Messenger\Test\Bus\TestBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/messenger-test/src/Bus/TestBus.php';

        $a = ($container->privates['debug.traced.messenger.bus.default'] ?? self::getDebug_Traced_Messenger_Bus_DefaultService($container));

        if (isset($container->services['messenger.bus.default.test-bus'])) {
            return $container->services['messenger.bus.default.test-bus'];
        }

        return $container->services['messenger.bus.default.test-bus'] = new \Zenstruck\Messenger\Test\Bus\TestBus('messenger.bus.default', $a);
    }
}
