<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxKRv3f\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxKRv3f/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerIxKRv3f.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerIxKRv3f\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerIxKRv3f\App_KernelTestDebugContainer([
    'container.build_hash' => 'IxKRv3f',
    'container.build_id' => '69f12d89',
    'container.build_time' => 1712512723,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxKRv3f');
