<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4ovVEq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4ovVEq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA4ovVEq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA4ovVEq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA4ovVEq\App_KernelDevDebugContainer([
    'container.build_hash' => 'A4ovVEq',
    'container.build_id' => '08c88496',
    'container.build_time' => 1712513362,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4ovVEq');
